version: '2'
services:

  # Application
  laravel-app:
    image: gcr.io/google-appengine/php:latest
    environment:
      - "DOCUMENT_ROOT=/app/public"
      - "SKIP_LOCKDOWN_DOCUMENT_ROOT=true"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_PASSWORD=secret"
    volumes:
      - ./:/app
    ports:
      - "80:8080"

  # Database
  laravel-db:
    image: mysql:5.6
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_HOST=172.26.1.0"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306"
