version: '2'
services:

  # Application
  laravel-app:
    ports:
      - "172.26.1.0:80:8080"
    networks:
      - test-network

  # Database
  laravel-db:
    volumes:
      - laravel_dbdata:/var/lib/mysql
    ports:
      - "172.26.1.0:3306:3306"
    networks:
      - test-network


volumes:
  laravel_dbdata:

networks:
  test-network:
    external:
      name: test-network
